name: Send email with a specific service
description: Send email with the well known services from nodemailer
author: Jon Uhlmann <hello@uhlmann.pro>
branding:
  icon: mail
  color: blue

inputs:
  service:
    description: Name of the service described at https://nodemailer.com/smtp/well-known
    default: iCloud
    required: true
  user:
    description: Username
    required: true
  pass:
    description: Password
    required: true
  from:
    description: The email address of the sender
    required: false
  sendMultipleEmails:
    description: Send multiple emails, and not all in one, (only for the to field, cc and bcc are always sent in the email)
    required: false
    default: false
  to:
    description: 'Comma separated list or an array of recipients email addresses that will appear on the To: field'
    required: true
  cc:
    description: 'Comma separated list or an array of recipients email addresses that will appear on the Cc: field'
    required: false
  bcc:
    description: 'Comma separated list or an array of recipients email addresses that will appear on the Bcc: field'
    required: false
  subject:
    description: The subject of the email
    default: Github Actions
    required: true
  text:
    description: 'The plaintext version of the message as an Unicode string, Buffer, Stream or an attachment-like object ({path: "/var/data/…"})'
    required: false
  html:
    description: 'The HTML version of the message as an Unicode string, Buffer, Stream or an attachment-like object ({path: "http://…"})'
    required: false

runs:
  using: node16
  main: main.mjs
