name: Test Action

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Send single email
        uses: ./
        with:
          replyTo: hello@account.pro
          priority: high
          service: '${{ secrets.MAIL_SERVICE }}'
          user: '${{ secrets.MAIL_USER }}'
          pass: '${{ secrets.MAIL_PASS }}'
          from: '${{ secrets.MAIL_FROM }}'
          to: '${{ secrets.MAIL_TO }}'
          subject: '${{ github.repository }} Project Build Results'
          text: |
            Status:
            ${{ job.status }}

            Data:
            ${{ toJson(github) }}
      - name: Send individual emails
        uses: ./
        with:
          priority: low
          individual: true
          service: '${{ secrets.MAIL_SERVICE }}'
          user: '${{ secrets.MAIL_USER }}'
          pass: '${{ secrets.MAIL_PASS }}'
          from: '${{ secrets.MAIL_FROM }}'
          to: '${{ secrets.MAIL_TO }}'
          subject: '${{ github.repository }} %name% Project Build Results'
          text: |
            Hello %name%
            I've sended multiple emails individual. Your address ist %email%.
